language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction

script: vendor/bin/phpunit